name: First Workflow

on: push

jobs:
  build:
    runs-on:

    steps:
      - uses: actions/checkout@v3
      - name: Run a simple github action
        run: echo "this workflow run successfully for this particular action"
